[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = """
  default-src 'self';
  script-src 'self' https://www.googletagmanager.com;
  connect-src 'self' https://www.google-analytics.com;
  img-src 'self' data:;
  style-src 'self';
  frame-src https://www.googletagmanager.com;
  worker-src 'self';
"""

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Accept-CH = "DPR, Width, Viewport-Width"
    Cache-Control = "public, max-age=31536000, immutable"
    Content-DPR = "1.0"
    Vary = "Accept, DPR, Width, Viewport-Width"

[[redirects]]
  from = "http://uplift-technologies.com/*"
  to = "https://uplift-technologies.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.uplift-technologies.com/*"
  to = "https://uplift-technologies.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.uplift-technologies.com/*"
  to = "https://uplift-technologies.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
